### ISSUE TITLE
Custom Electrum server - Account discovery error for SegWit accounts

### ISSUE THREAD

**Issue by simple-guy1** [trezor/trezor-suite#9391]
**Describe the bug**
When I connect to my own electrum server running on localhost, Trezor Suite can only find my Taproot based accounts, but can't find SegWit based accounts with error message "Account discovery error".

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app
-   Browser: Version 23.8.1 (23.8.1.30429)
-   OS: MacOS Ventura 13.5.1, Apple M2
-   Bridge: ?
-   Firmware Version: Trezor One, 1.12.1
-   Version of Custom Electrum Server: https://hub.docker.com/r/lukechilds/electrumx 
**How to reproduce**

1. Switch to custom electrum custom server for Bitcoin
2. Switch to Accounts
3. Error appears

**Expected behavior**
Expected behaviour is that Trezor Suite finds my SegWit accounts as finds for my Taproot accounts

**Additional context**
When I connect Sparrow wallet to same custom electrum server and load there xpub for one of my SegWit accounts, which Trezor Suite cant find, Sparrow finds its transactions.

**Custom Electrum Server**
- version: https://hub.docker.com/r/lukechilds/electrumx 
- running in docker
- docker-compose.yml
```
version: "3"

services:
  electrumx:
    image: lukechilds/electrumx
    container_name: electrumx
    restart: unless-stopped
    expose:
      - "50002"
      - "50001"
    ports:
      - "50002:50002"
      - "50001:50001"
    volumes:
      - "electrumx_data:/data"
    environment:
      - DAEMON_URL=user:pasword@bitcoind:8332
      - COIN=Bitcoin
      - PEER_DISCOVERY=self
      - SERVICES=tcp://:50001,ssl://:50002,tcp://127.0.0.1:50001    
    networks:
      - electrum

volumes:
  electrumx_data:

networks:
  electrum:
    external: true
```
